version: '3.8'

services:
  config-server:
    build: ../config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka-server:
    build: ../eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway-service:
    build: ../api-gateway-service
    container_name: api-gateway-service
    ports:
      - "80:8080"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ecommerce-network

  inventory-service:
    build: ../inventory-service
    container_name: inventory-service
    depends_on:
      - config-server
      - eureka-server
      - inventory-service-postgres-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ecommerce-network

  inventory-service-postgres-db:
    image: postgres:16
    container_name: inventory-service-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_db
    networks:
      - ecommerce-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  payment-service:
    build: ../payment-service
    container_name: payment-service
    ports:
      - "8089:8089"
      - "8090:8090"
    networks:
      - ecommerce-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  ecommerce-network:
    driver: bridge

volumes:
  postgres_data:
