export enum OrderStatus {
  CREATED='CREATED',
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED='DELIVERED',
  FINISHED = 'FINISHED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
