server:
  port: 8888  # Standard port for the Config Server

spring:
  application:
    name: config-server
  config:
    activate:
      on-profile: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dvoracek-martin/ecommerce-config-repo
          default-label: main
          clone-on-start: true
          search-paths: local
